### ISSUE TITLE
学习Github

### ISSUE THREAD

**Issue by DistChen** [red-fear/KnowledgeCenter#1]
1. 知道并了解Github中的重要功能，如：分支`Branch`、标签`Tag`、`issue`等，[点击参考](https://www.liaoxuefeng.com/wiki/896043488029600)；
2. 学习Markdown的基本语法，[点击学习](https://www.jianshu.com/p/191d1e21f7ed)。
      >可以直接为这个仓库生成`README.md`文件，然后在这个`README.md`文件中书写你学习到的语法，确保生成的内容无误，如插入标题、图标、表格、列表等。

**注意：** 这两个学习内容都不需要完全掌握，只需要达到：
- 大致知道git是什么，有什么功能即可。众多的命令不需要每一个都掌握，掌握主要的clone、pull、commit、push等几个命令即可；
- 在自己的电脑上安装好git客户端并能通过ssh直连，[点击参考](https://blog.csdn.net/u013778905/article/details/83501204)；
- 了解Markdown的基本使用即可，不用死记硬背每一个语法，比如你只需要知道通过markdown能插入表格、图片等内容就行，具体插入表格、图片的语法是怎样的，用到就查，用的多了就知道了。

**学习成果：** 要求能将此仓库从Github克隆到自己的电脑，并在自己的本地仓库中添加README.md文件，文件内有标题、图片、表格等不同语法内容体现，并将本地添加的内容提交到Github远程仓库。

**Comment by red-fear** [comment]
### learn github
####1.安装 git
(```)
+$ git config --global user.name "Your Name"
+$ git config --global user.email "email@example.com"
(```)
####2.创建版本库
+先在本地建一个文件夹，在此文件夹中打开git命令提示符界面，然后`$ git init`
+`$ git add <file>`添加文件至仓库
+`$ git commit -m "my first file"`提交文件至仓库
####3.基本操作
+`$ git log`显示提交的日志历史
+`$ git log --pretty=oneline`将日志线性化
+`$ git relog`查看历史命令
+`$ git reset --hard HEAD^`回退至上一版本
+`$ git reset --hard HEAD~100`回退至上一百版本
+`$ git reset HEAD file.txt`撤销file.txt缓存区的修改
+`$ git status`查看状态
+`$ git HEAD file.txt`比较工作区和缓存区
+`$ git diff HEAD --file.txt`查看工作区和版本库里面最新版本的区别
+`$ git checkout --file.txt`丢弃对文件file.txt的工作区的修改
从版本库中删除文件：
+`$ git rm file.txt`
提交删除:
+`$ git commit -m "remove file.txt"`
####4.分支管理
+`$ git checkout -b fenzhi1`建立新分支
+`$ git dranch`查看当前分支
+`$ git checkout master`切换至master分支
+`$ git merge fenzhi1`将分支1与其母分支合并
+`$ git branch -d fenzhi1`删除分支1
查看分支图：
+`$ git log --graph --pretty=oneline --abbrev-commit`
强制删除分支1：
+`$ git checkout -D fenzhi1`
查看远程库信息：
+`$ git remote`
+`$ git remote -v`显示细节
推送分支1至origin：
+`$ git push origin fenzhi1
在本地创建与远程分支对应的分支：
+`$ git checkout -b fenzhi2 origin/fenzhi2`只管修改分支2，不时合并分支（git add然后git commit）
若推送失败：
+`$ git pull`来抓取分支
若抓取失败：
先`$ git branch --set-upstream-to=origin/fenzhi2 fenzhi2`建立本地分支和远程分支的关联
再抓取`$ git pull`,然后在解决了冲突后git commit并`$ git push origin fenzhi2`即可
把本地未push的分叉提交历史整理成直线：`$ git rebase`
++++++
####总结：我认为git的作用大致分为以下几类:
+记录下文件的修改，在改动错误等需求下，可以根据记录的历史修改，将文件恢复至未修改前的某个适当的版本；
+建立新的分支，再对新的分支进行修改，当新的分支符合修改要求时，可合并分支，避免了直接改动源文件带来错误后的不已恢复性；
+可以多人共同对同一个文件进行开发，每个人建立不同的分支，并对自己负责的分支进行改动即可，最后商榷后合并为同至源文件，即可完成源文件的修改；
####特点：
+从分支进行修改时，大可不必为改动出错而烦恼；
+可以多人多个时间段多个地点对同一文件的不同部分进行修改；
+可以“后悔”，在修改出错时可以进行版本的回退；
+进行的分支修改情况对组员透明，方便其他人理解。
