### ISSUE TITLE
了解SSH

### ISSUE THREAD

**Issue by DistChen** [red-fear/KnowledgeCenter#2]
git中使用到了SSH，需要知道为什么要使用SSH，使用它有什么好处，可参考：
- https://blog.csdn.net/u013452337/article/details/80847113

只需要知道SSH是什么，为什么用它，大致有个印象就行，不要投入到细节。

> 注意：所有这些工具辅助类的东西都不需要投入细节当中，知道是什么，会大致使用即可。

**Comment by red-fear** [comment]
[SSH.docx](https://github.com/red-fear/KnowledgeCenter/files/3940380/SSH.docx)
